python src/optmaven.py --exclude_hetero yes < scripts/1acy.sh
python src/optmaven.py --exclude_hetero yes < scripts/1ce1.sh
python src/optmaven.py --exclude_hetero yes < scripts/1cft.sh
python src/optmaven.py --exclude_hetero yes < scripts/1dzb.sh
python src/optmaven.py --exclude_hetero yes < scripts/1egj.sh
python src/optmaven.py --exclude_hetero yes < scripts/1f90.sh
python src/optmaven.py --exclude_hetero yes < scripts/1fpt.sh
python src/optmaven.py --exclude_hetero yes < scripts/1hh6.sh
python src/optmaven.py --exclude_hetero yes < scripts/1i8i.sh
python src/optmaven.py --exclude_hetero yes < scripts/1jhl.sh
python src/optmaven.py --exclude_hetero yes < scripts/1jrh.sh
python src/optmaven.py --exclude_hetero yes < scripts/1kc5.sh
python src/optmaven.py --exclude_hetero yes < scripts/1kiq.sh
python src/optmaven.py --exclude_hetero yes < scripts/1mlc.sh
python src/optmaven.py --exclude_hetero yes < scripts/1nak.sh
python src/optmaven.py --exclude_hetero yes < scripts/1obe.sh
python src/optmaven.py --exclude_hetero yes < scripts/1pz5.sh
python src/optmaven.py --exclude_hetero yes < scripts/1qnz.sh
python src/optmaven.py --exclude_hetero yes < scripts/1sm3.sh
python src/optmaven.py --exclude_hetero yes < scripts/1tqb.sh
python src/optmaven.py --exclude_hetero yes < scripts/1tzh.sh
python src/optmaven.py --exclude_hetero yes < scripts/1u8j.sh
python src/optmaven.py --exclude_hetero yes < scripts/1v7m.sh
python src/optmaven.py --exclude_hetero yes < scripts/1xgy.sh
python src/optmaven.py --exclude_hetero yes < scripts/1za3.sh
python src/optmaven.py --exclude_hetero yes < scripts/2a6i.sh
python src/optmaven.py --exclude_hetero yes < scripts/2bdn.sh
python src/optmaven.py --exclude_hetero yes < scripts/2dqj.sh
python src/optmaven.py --exclude_hetero yes < scripts/2fjh.sh
python src/optmaven.py --exclude_hetero yes < scripts/2h1p.sh
python src/optmaven.py --exclude_hetero yes < scripts/2hh0.sh
python src/optmaven.py --exclude_hetero yes < scripts/2hrp.sh
python src/optmaven.py --exclude_hetero yes < scripts/2iff.sh
python src/optmaven.py --exclude_hetero yes < scripts/2jel.sh
python src/optmaven.py --exclude_hetero yes < scripts/2or9.sh
python src/optmaven.py --exclude_hetero yes < scripts/2qr0.sh
python src/optmaven.py --exclude_hetero yes < scripts/2r29.sh
python src/optmaven.py --exclude_hetero yes < scripts/2vxs.sh
python src/optmaven.py --exclude_hetero yes < scripts/3ab0.sh
python src/optmaven.py --exclude_hetero yes < scripts/3cvh.sh
python src/optmaven.py --exclude_hetero yes < scripts/3d85.sh
python src/optmaven.py --exclude_hetero yes < scripts/3e8u.sh
python src/optmaven.py --exclude_hetero yes < scripts/3etb.sh
python src/optmaven.py --exclude_hetero yes < scripts/3f58.sh
python src/optmaven.py --exclude_hetero yes < scripts/3g6d.sh
python src/optmaven.py --exclude_hetero yes < scripts/3ghe.sh
python src/optmaven.py --exclude_hetero yes < scripts/3hr5.sh
python src/optmaven.py --exclude_hetero yes < scripts/3ks0.sh
python src/optmaven.py --exclude_hetero yes < scripts/3lqa.sh
python src/optmaven.py --exclude_hetero yes < scripts/3mls.sh
python src/optmaven.py --exclude_hetero yes < scripts/3mlx.sh
python src/optmaven.py --exclude_hetero yes < scripts/3nfp.sh
python src/optmaven.py --exclude_hetero yes < scripts/3o0r.sh
python src/optmaven.py --exclude_hetero yes < scripts/3p30.sh
python src/optmaven.py --exclude_hetero yes < scripts/3qg6.sh
python src/optmaven.py --exclude_hetero yes < scripts/3rkd.sh
