python src/optmaven.py --exclude_hetero yes < scripts/1bj1.sh
python src/optmaven.py --exclude_hetero yes < scripts/1cfs.sh
python src/optmaven.py --exclude_hetero yes < scripts/1cu4.sh
python src/optmaven.py --exclude_hetero yes < scripts/1e4w.sh
python src/optmaven.py --exclude_hetero yes < scripts/1ejo.sh
python src/optmaven.py --exclude_hetero yes < scripts/1fbi.sh
python src/optmaven.py --exclude_hetero yes < scripts/1ggi.sh
python src/optmaven.py --exclude_hetero yes < scripts/1hin.sh
python src/optmaven.py --exclude_hetero yes < scripts/1i9r.sh
python src/optmaven.py --exclude_hetero yes < scripts/1jp5.sh
python src/optmaven.py --exclude_hetero yes < scripts/1kb5.sh
python src/optmaven.py --exclude_hetero yes < scripts/1kcr.sh
python src/optmaven.py --exclude_hetero yes < scripts/1ktr.sh
python src/optmaven.py --exclude_hetero yes < scripts/1mvu.sh
python src/optmaven.py --exclude_hetero yes < scripts/1oaz.sh
python src/optmaven.py --exclude_hetero yes < scripts/1p4b.sh
python src/optmaven.py --exclude_hetero yes < scripts/1qkz.sh
python src/optmaven.py --exclude_hetero yes < scripts/1rjl.sh
python src/optmaven.py --exclude_hetero yes < scripts/1tet.sh
python src/optmaven.py --exclude_hetero yes < scripts/1tzg.sh
python src/optmaven.py --exclude_hetero yes < scripts/1tzi.sh
python src/optmaven.py --exclude_hetero yes < scripts/1uwx.sh
python src/optmaven.py --exclude_hetero yes < scripts/1w72.sh
python src/optmaven.py --exclude_hetero yes < scripts/1ztx.sh
python src/optmaven.py --exclude_hetero yes < scripts/2b1h.sh
python src/optmaven.py --exclude_hetero yes < scripts/2ck0.sh
python src/optmaven.py --exclude_hetero yes < scripts/2eh8.sh
python src/optmaven.py --exclude_hetero yes < scripts/2g5b.sh
python src/optmaven.py --exclude_hetero yes < scripts/2hfg.sh
python src/optmaven.py --exclude_hetero yes < scripts/2hkf.sh
python src/optmaven.py --exclude_hetero yes < scripts/2hvk.sh
python src/optmaven.py --exclude_hetero yes < scripts/2j4w.sh
python src/optmaven.py --exclude_hetero yes < scripts/2oqj.sh
python src/optmaven.py --exclude_hetero yes < scripts/2osl.sh
python src/optmaven.py --exclude_hetero yes < scripts/2qsc.sh
python src/optmaven.py --exclude_hetero yes < scripts/2vwe.sh
python src/optmaven.py --exclude_hetero yes < scripts/2zpk.sh
python src/optmaven.py --exclude_hetero yes < scripts/3bae.sh
python src/optmaven.py --exclude_hetero yes < scripts/3cxd.sh
python src/optmaven.py --exclude_hetero yes < scripts/3dvg.sh
python src/optmaven.py --exclude_hetero yes < scripts/3eo1.sh
python src/optmaven.py --exclude_hetero yes < scripts/3eyu.sh
python src/optmaven.py --exclude_hetero yes < scripts/3fn0.sh
python src/optmaven.py --exclude_hetero yes < scripts/3ggw.sh
python src/optmaven.py --exclude_hetero yes < scripts/3gjg.sh
python src/optmaven.py --exclude_hetero yes < scripts/3iu3.sh
python src/optmaven.py --exclude_hetero yes < scripts/3l5y.sh
python src/optmaven.py --exclude_hetero yes < scripts/3mlr.sh
python src/optmaven.py --exclude_hetero yes < scripts/3mlw.sh
python src/optmaven.py --exclude_hetero yes < scripts/3mly.sh
python src/optmaven.py --exclude_hetero yes < scripts/3nh7.sh
python src/optmaven.py --exclude_hetero yes < scripts/3o2d.sh
python src/optmaven.py --exclude_hetero yes < scripts/3pjs.sh
python src/optmaven.py --exclude_hetero yes < scripts/3qwo.sh
